export const features = [
    "Craftsmanship",
    "Material Quality",
    "Design Expertise",
    "Durability Guarantee",
    "International Standards",
    "Customer Service",
    "Innovation",
    "Trust & Reliability",
    "After-Sales Support",
    "Value for Money",
    "Cultural Sensitivity",
    "Professional Collaboration",
    "Technical Expertise",
    "Community Involvement",
    "Antique Replicas",
    "Premium Materials",
    "Customized Design",
    "Durability and Quality",
    "Global Standards Compliance",
    "Comprehensive Customer Care",
    "Technological Innovation",
    "Established Trust",
    "After-Sales Support",
    "Transparent Value",
    "Cultural Sensitivity",
    "Collaboration with Designers",
    "Marble Expertise",
    "Community Endorsement",
  ];

export  const Stone = [
    "25 years of trusted excellence",
    "Premium Australian marble",
    "Custom, modern-traditional fusion",
    "Long-lasting beauty assurance",
    "Global quality benchmarks",
    "End-to-end personalized service",
    "Latest design and tech adoption",
    "Legacy of trust with clients",
    "Comprehensive support",
    "Quality and satisfaction focus",
    "Culturally nuanced designs",
    "Works with designers",
    "Specialized marble knowledge",
    "Active community engagement",
    "25+ Years Experience",
    "Sustainable Sourcing",
    "Tradition & Modernity",
    "Assured",
    "International Quality",
    "Personalized Service",
    "Cutting-Edge Design",
    "Proven Reliability",
    "Ongoing Assistance",
    "No Hidden Costs",
    "Respectful Design",
    "Professional Harmony",
    "Specialized Knowledge",
    "Customer-Driven",
  ];

 export const localVendor = [
    "Vandalism-prone",
    "Inconsistent quality",
    "Limited, templated designs",
    "Limited or no guarantee",
    "May not meet standards",
    "Fragmented services",
    "Slower to innovate",
    "Varies widely",
    "Often limited support",
    "Hidden long-term costs",
    "May lack cultural insight",
    "Limited collaboration",
    "General Knowledge",
    "Minimal community input",
    "May Vary",
    "Inconsistent",
    "Limited Options",
    "Questionable",
    "Unverified",
    "Fragmented Support",
    "Rarely Updated",
    "Uncertain",
    "Limited",
    "Potential Extras",
    "May Lack Insight",
    "Not Common",
    "General Know-how",
    "Minimal Interaction",
  ];
